### ISSUE TITLE
errno: 16/"Device or resource busy"

### ISSUE THREAD

**Issue by WeaselSauce** [Dreae/compressor#10]
Hi there and thanks in advance.  I've been unable to run the compressor binary after successful make / install on Ubuntu 20.04 due to the following error:

`src/compressor_cache_user.c:xsk_configure:511: Assertion failed: bind(sfd, (struct sockaddr *)&sxdp, sizeof(sxdp)) == 0: errno: 16/"Device or resource busy"`

Any permutation of configuration file settings results in the same outcome, so long as I set the interface setting to the active public interface on which the primary IP is bound (in this case eth0).  Let me know if I'm missing anything or can provide more info.

**Comment by WeaselSauce** [comment]
`
root@grevps1:~/compressor/src# uname -a
Linux grevps1 5.4.0-62-generic #70-Ubuntu SMP Tue Jan 12 12:45:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by gamemann** [comment]
Can you try running Compressor with `force_skb = 1;` inside of `/etc/compressor/compressor.conf`? This will force the XDP program to attach to the hook after SKB allocation. It won't be as fast as DRV mode, but I've noticed a lot of issues regarding the AF_XDP sockets and XDP DRV mode, specifically when using the `virtio_net` driver. Though, it could be impacting all drivers.

You may also want to try implementing the changes in this PR request I made.

https://github.com/Dreae/compressor/pull/8

If you have multiple RX queues, you'll need to setup each AF_XDP socket on the appropriate RX queue since the XDP program redirects it to the AF_XDP socket depending on the RX queue it comes in within the hardware itself. The above PR should do this.

**Comment by WeaselSauce** [comment]
force_skb = 1; had no impact, but will test with the PR changes and update

**Comment by WeaselSauce** [comment]
The patch does appear to have resolved the issue!

**Comment by gamemann** [comment]
Interesting. The PR changes should make it so the program doesn't exit if it cannot bind to the AF_XDP socket. Though, if you want A2S_INFO caching/responses to work properly, AF_XDP sockets on each RX queue need to be bound to.

How many RX queues do you have? I normally list the `/sys/class/net/<interface>/queues/` to find out how many. You can also use `ethtool` via `ethtool -l <interface>` as well if you have that installed.

With that said, can you do `lshw -class network` (as root) and see what net driver you're using?

**Comment by gamemann** [comment]
I'm glad that resolved the issue! I'm going to keep my above comment since it would be important if you want A2S_INFO caching and responses to work.

**Comment by WeaselSauce** [comment]
Thanks for that.  For posterity:

`
root@grevps1:~# lshw -class network
  *-network
       description: Ethernet interface
       physical id: 1
       logical name: eth0
       serial: 00:16:3e:26:ef:87
       capabilities: ethernet physical
       configuration: broadcast=yes driver=vif ip=74.91.125.51 link=yes multicast=yes
`

`
root@grevps1:~# ls /sys/class/net/eth0/queues/
rx-0  rx-1  rx-2  rx-3  tx-0  tx-1  tx-2  tx-3
`
